//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACTICA_AEAE_3_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDfacturacion : DbContext
    {
        public BDfacturacion()
            : base("name=BDfacturacion")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLCATEGORIA_PROD> TBLCATEGORIA_PROD { get; set; }
        public virtual DbSet<TBLCLIENTES> TBLCLIENTES { get; set; }
        public virtual DbSet<TBLDETALLE_FACTURA> TBLDETALLE_FACTURA { get; set; }
        public virtual DbSet<TBLEMPLEADO> TBLEMPLEADO { get; set; }
        public virtual DbSet<TBLESTADO_FACTURA> TBLESTADO_FACTURA { get; set; }
        public virtual DbSet<TBLFACTURA> TBLFACTURA { get; set; }
        public virtual DbSet<TBLPRODUCTO> TBLPRODUCTO { get; set; }
        public virtual DbSet<TBLROLES> TBLROLES { get; set; }
        public virtual DbSet<TBLSEGURIDAD> TBLSEGURIDAD { get; set; }
    }
}
